from app.models import Direction, DirectionProductLink, Product, ProductSyncSource, UserProfile


USERS: dict[str, UserProfile] = {
    "u_001": UserProfile(
        user_id="u_001",
        username="runner_chen",
        long_term_interests=["运动鞋", "健身装备", "跑步"],
        recent_interests=["马拉松", "缓震", "透气"],
        brand_preference=["Nike", "Adidas"],
        price_min=300,
        price_max=700,
        negative_tags=["皮鞋"],
    ),
    "u_002": UserProfile(
        user_id="u_002",
        username="home_life",
        long_term_interests=["家居", "收纳", "厨房"],
        recent_interests=["咖啡", "餐具"],
        brand_preference=["IKEA", "MUJI"],
        price_min=50,
        price_max=350,
        negative_tags=["运动鞋"],
    ),
    "u_003": UserProfile(
        user_id="u_003",
        username="beauty_sara",
        long_term_interests=["护肤", "美妆", "精华", "面膜"],
        recent_interests=["抗老", "玻尿酸", "防晒", "成分党"],
        brand_preference=["珀莱雅", "可复美", "薇诺娜"],
        price_min=80,
        price_max=600,
        negative_tags=["重金属", "酒精"],
    ),
    "u_004": UserProfile(
        user_id="u_004",
        username="tech_wang",
        long_term_interests=["数码", "耳机", "键盘", "智能设备"],
        recent_interests=["降噪", "无线", "机械键盘", "Type-C"],
        brand_preference=["索尼", "苹果", "罗技"],
        price_min=200,
        price_max=2000,
        negative_tags=["有线", "杂牌"],
    ),
    "u_005": UserProfile(
        user_id="u_005",
        username="pet_lover_liu",
        long_term_interests=["宠物", "猫咪", "狗狗", "宠物食品"],
        recent_interests=["冻干", "自动喂食", "宠物健康", "营养补充"],
        brand_preference=["皇家", "麦富迪", "小佩"],
        price_min=30,
        price_max=500,
        negative_tags=["人工色素", "防腐剂"],
    ),
}


PRODUCTS: list[Product] = [
    # ── 原有商品 ──────────────────────────────────────
    Product(
        product_id="p_001",
        title="轻量缓震跑鞋",
        category="运动鞋",
        brand="Adidas",
        price=499,
        description="适合日常慢跑和长距离训练的轻量跑鞋。",
        features=["缓震", "透气", "轻量", "长跑"],
        image_url="https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        stock=120,
        rating=4.8,
    ),
    Product(
        product_id="p_002",
        title="马拉松训练运动短裤",
        category="健身装备",
        brand="Nike",
        price=219,
        description="速干面料，适合跑步训练和健身运动。",
        features=["速干", "跑步", "训练", "透气"],
        image_url="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f",
        stock=80,
        rating=4.6,
    ),
    Product(
        product_id="p_003",
        title="真皮商务皮鞋",
        category="皮鞋",
        brand="Clarks",
        price=899,
        description="商务通勤场景使用的正装皮鞋。",
        features=["商务", "真皮", "通勤"],
        image_url="https://images.unsplash.com/photo-1614252369475-531eba835eb1",
        stock=45,
        rating=4.4,
    ),
    Product(
        product_id="p_004",
        title="家用手冲咖啡套装",
        category="厨房",
        brand="MUJI",
        price=268,
        description="适合家庭咖啡爱好者的入门手冲套装。",
        features=["咖啡", "厨房", "家居", "礼物"],
        image_url="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085",
        stock=64,
        rating=4.7,
    ),
    Product(
        product_id="p_005",
        title="模块化桌面收纳盒",
        category="收纳",
        brand="IKEA",
        price=89,
        description="适合办公桌、化妆台和书桌的模块化收纳盒。",
        features=["收纳", "家居", "办公", "模块化"],
        image_url="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85",
        stock=200,
        rating=4.5,
    ),
    Product(
        product_id="p_006",
        title="专业跑步压缩袜",
        category="健身装备",
        brand="Nike",
        price=129,
        description="跑步训练时提供包裹感和支撑感。",
        features=["跑步", "训练", "支撑", "透气"],
        image_url="https://images.unsplash.com/photo-1556906781-9a412961c28c",
        stock=150,
        rating=4.6,
    ),

    # ── 美妆护肤 ──────────────────────────────────────
    Product(
        product_id="p_007",
        title="双重玻尿酸次抛精华",
        category="护肤",
        brand="可复美",
        price=189,
        description="高低分子双重玻尿酸，快速补水锁水，次抛设计卫生方便。",
        features=["玻尿酸", "补水", "保湿", "次抛", "敏感肌"],
        image_url="https://images.unsplash.com/photo-1556228720-195a672e8a03",
        stock=320,
        rating=4.8,
    ),
    Product(
        product_id="p_008",
        title="早C晚A维C亮肤精华",
        category="护肤",
        brand="珀莱雅",
        price=269,
        description="早晨使用维C提亮抗氧化，均匀肤色，改善暗沉。",
        features=["维C", "亮肤", "抗氧化", "提亮", "早C"],
        image_url="https://images.unsplash.com/photo-1620916566398-39f1143ab7be",
        stock=210,
        rating=4.7,
    ),
    Product(
        product_id="p_009",
        title="氨基酸温和洁面乳",
        category="护肤",
        brand="薇诺娜",
        price=128,
        description="氨基酸表活，pH值温和，适合敏感肌和干皮日常洁面。",
        features=["氨基酸", "温和", "敏感肌", "洁面", "低刺激"],
        image_url="https://images.unsplash.com/photo-1556228578-8c89e6adf883",
        stock=280,
        rating=4.6,
    ),
    Product(
        product_id="p_010",
        title="视黄醇A醇紧致晚霜",
        category="护肤",
        brand="珀莱雅",
        price=359,
        description="0.1%视黄醇配方，夜间修护，改善细纹和松弛。",
        features=["视黄醇", "A醇", "抗老", "紧致", "晚霜"],
        image_url="https://images.unsplash.com/photo-1583241475880-083f84372725",
        stock=180,
        rating=4.7,
    ),
    Product(
        product_id="p_011",
        title="SPF50+隔离防晒霜",
        category="护肤",
        brand="安耐晒",
        price=168,
        description="轻薄不油腻，防晒同时兼顾日常隔离，适合通勤户外。",
        features=["防晒", "SPF50+", "轻薄", "隔离", "户外"],
        image_url="https://images.unsplash.com/photo-1526758097130-bab247274312",
        stock=350,
        rating=4.8,
    ),
    Product(
        product_id="p_012",
        title="花西子雕花气垫粉底",
        category="彩妆",
        brand="花西子",
        price=298,
        description="东方雕花设计，持久遮瑕，透气不卡粉，适合日常通勤妆容。",
        features=["气垫", "遮瑕", "持久", "国潮", "通勤妆"],
        image_url="https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
        stock=160,
        rating=4.5,
    ),

    # ── 3C 数码 ───────────────────────────────────────
    Product(
        product_id="p_013",
        title="索尼WF-1000XM5真无线降噪耳机",
        category="耳机",
        brand="索尼",
        price=1799,
        description="行业顶级主动降噪，LDAC高清音质，单次续航8小时。",
        features=["降噪", "无线", "LDAC", "高音质", "长续航"],
        image_url="https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
        stock=85,
        rating=4.9,
    ),
    Product(
        product_id="p_014",
        title="华为WATCH GT 5智能手表",
        category="智能设备",
        brand="华为",
        price=1288,
        description="14天超长续航，全天候心率血氧监测，适合运动健康管理。",
        features=["智能手表", "健康监测", "长续航", "运动", "GPS"],
        image_url="https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        stock=120,
        rating=4.7,
    ),
    Product(
        product_id="p_015",
        title="罗技MX Keys S无线机械键盘",
        category="电脑配件",
        brand="罗技",
        price=899,
        description="低音触感轴，多设备无线切换，背光可调，适合长时间办公。",
        features=["无线", "机械键盘", "低噪音", "多设备", "背光"],
        image_url="https://images.unsplash.com/photo-1587829741301-dc798b83add3",
        stock=95,
        rating=4.6,
    ),
    Product(
        product_id="p_016",
        title="Anker氮化镓65W三口充电器",
        category="电源配件",
        brand="Anker",
        price=219,
        description="氮化镓技术，65W快充，USB-C+A三口同时充，体积小巧。",
        features=["氮化镓", "快充", "Type-C", "多口", "轻便"],
        image_url="https://images.unsplash.com/photo-1583394293914-5d2f48e76b55",
        stock=300,
        rating=4.8,
    ),
    Product(
        product_id="p_017",
        title="罗技MX Master 3S无线鼠标",
        category="电脑配件",
        brand="罗技",
        price=549,
        description="MagSpeed磁吸滚轮，8000DPI高精度，人体工学设计适合长时间使用。",
        features=["无线", "人体工学", "高精度", "静音", "办公"],
        image_url="https://images.unsplash.com/photo-1527864550417-7fd91fc51a46",
        stock=110,
        rating=4.8,
    ),
    Product(
        product_id="p_018",
        title="JBL Flip 6便携蓝牙音箱",
        category="音频设备",
        brand="JBL",
        price=599,
        description="IP67防水防尘，12小时续航，PartyBoost多台连接，户外必备。",
        features=["防水", "便携", "蓝牙", "户外", "长续航"],
        image_url="https://images.unsplash.com/photo-1608043152269-423dbba4e7e1",
        stock=140,
        rating=4.7,
    ),

    # ── 宠物用品 ──────────────────────────────────────
    Product(
        product_id="p_019",
        title="小佩智能自动喂食器5L",
        category="宠物用品",
        brand="小佩",
        price=399,
        description="APP远程控制，定时定量喂食，语音互动，适合猫狗。",
        features=["自动喂食", "APP控制", "定时", "语音互动", "猫狗通用"],
        image_url="https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba",
        stock=200,
        rating=4.7,
    ),
    Product(
        product_id="p_020",
        title="麦富迪鸡肉冻干猫零食",
        category="宠物食品",
        brand="麦富迪",
        price=89,
        description="100%纯鸡肉冻干，无添加防腐剂，高蛋白低脂肪，猫咪零食首选。",
        features=["冻干", "无添加", "高蛋白", "纯肉", "猫零食"],
        image_url="https://images.unsplash.com/photo-1548767797-d8c844163c4c",
        stock=450,
        rating=4.8,
    ),
    Product(
        product_id="p_021",
        title="皇家幼猫专用猫粮2kg",
        category="宠物食品",
        brand="皇家",
        price=168,
        description="针对4-12月幼猫配方，高DHA支持大脑发育，均衡营养。",
        features=["幼猫", "DHA", "均衡营养", "皇家", "猫粮"],
        image_url="https://images.unsplash.com/photo-1592194996308-7b43878e84a6",
        stock=280,
        rating=4.7,
    ),
    Product(
        product_id="p_022",
        title="小佩宠物智能循环饮水机",
        category="宠物用品",
        brand="小佩",
        price=259,
        description="三重过滤系统，活水循环，鼓励宠物多喝水，预防泌尿问题。",
        features=["循环过滤", "活水", "智能", "猫狗通用", "泌尿健康"],
        image_url="https://images.unsplash.com/photo-1450778869180-41d0601e046e",
        stock=190,
        rating=4.6,
    ),
    Product(
        product_id="p_023",
        title="宠物猫抓板剑麻磨爪柱",
        category="宠物玩具",
        brand="米妮",
        price=69,
        description="天然剑麻材质，稳固底座防倾倒，附带逗猫棒，适合室内猫咪。",
        features=["磨爪", "剑麻", "稳固", "逗猫棒", "室内猫"],
        image_url="https://images.unsplash.com/photo-1587300003388-59208cc962cb",
        stock=320,
        rating=4.5,
    ),
    Product(
        product_id="p_024",
        title="宠物营养膏益生菌补充剂",
        category="宠物保健",
        brand="卫仕",
        price=128,
        description="益生菌+牛磺酸配方，改善肠胃消化，增强免疫力，适合猫狗。",
        features=["益生菌", "营养", "肠胃健康", "免疫力", "猫狗通用"],
        image_url="https://images.unsplash.com/photo-1583337130417-3346a1be7dee",
        stock=240,
        rating=4.6,
    ),
]


DIRECTIONS: list[Direction] = [
    Direction(
        direction_id="d_running_beginner",
        title="基础跑步训练装备",
        category="健身装备",
        description="适合想开始跑步训练的人，从核心装备和低门槛搭配开始。",
        target_scene="日常训练",
        budget_min=120,
        budget_max=700,
        difficulty_level="入门",
        target_interests=["跑步", "训练", "缓震", "透气", "长跑"],
    ),
    Direction(
        direction_id="d_coffee_beginner",
        title="入门手冲咖啡",
        category="厨房",
        description="适合想在家开始手冲咖啡的人，预算适中，学习门槛低。",
        target_scene="家用入门",
        budget_min=100,
        budget_max=400,
        difficulty_level="入门",
        target_interests=["咖啡", "厨房", "手冲", "家居"],
    ),
    Direction(
        direction_id="d_home_organizing",
        title="桌面与家居收纳优化",
        category="收纳",
        description="适合想先提升生活整洁度的人，从收纳和桌面组织开始。",
        target_scene="家居整理",
        budget_min=50,
        budget_max=300,
        difficulty_level="低门槛",
        target_interests=["收纳", "家居", "办公", "模块化"],
    ),
    Direction(
        direction_id="d_skincare_starter",
        title="护肤入门：补水抗氧化基础套路",
        category="护肤",
        description="适合刚开始建立护肤习惯的人，从洁面、精华、防晒三步走，成分温和，见效稳定。",
        target_scene="日常护肤",
        budget_min=200,
        budget_max=800,
        difficulty_level="入门",
        target_interests=["护肤", "补水", "保湿", "防晒", "敏感肌"],
    ),
    Direction(
        direction_id="d_skincare_advanced",
        title="进阶抗老：早C晚A精华路线",
        category="护肤",
        description="适合已有基础护肤习惯、想进一步改善肤质的人，主打维C亮肤和视黄醇抗老。",
        target_scene="功效护肤",
        budget_min=400,
        budget_max=1200,
        difficulty_level="进阶",
        target_interests=["抗老", "维C", "视黄醇", "A醇", "成分党"],
    ),
    Direction(
        direction_id="d_tech_audio",
        title="个人音频升级：无线降噪耳机",
        category="耳机",
        description="适合想从有线耳机升级到真无线降噪的用户，兼顾通勤、居家和运动场景。",
        target_scene="通勤居家",
        budget_min=500,
        budget_max=2000,
        difficulty_level="低门槛",
        target_interests=["降噪", "无线", "耳机", "音质", "通勤"],
    ),
    Direction(
        direction_id="d_tech_workspace",
        title="桌面生产力升级：键鼠外设套装",
        category="电脑配件",
        description="适合在家办公或学习效率有提升需求的用户，从键盘、鼠标和充电器开始。",
        target_scene="居家办公",
        budget_min=600,
        budget_max=2000,
        difficulty_level="低门槛",
        target_interests=["键盘", "鼠标", "无线", "办公", "效率"],
    ),
    Direction(
        direction_id="d_pet_new_cat",
        title="新手养猫入门清单",
        category="宠物用品",
        description="适合第一次养猫的新手，从自动喂食、饮水、猫粮和基础玩具搭建起完整的养猫环境。",
        target_scene="新手养猫",
        budget_min=300,
        budget_max=1000,
        difficulty_level="入门",
        target_interests=["猫咪", "自动喂食", "猫粮", "宠物健康", "新手"],
    ),
    Direction(
        direction_id="d_pet_health",
        title="宠物健康管理：营养与日常护理",
        category="宠物保健",
        description="适合希望系统提升宠物健康状态的主人，从主食品质、零食选择到营养补充剂全面升级。",
        target_scene="宠物健康",
        budget_min=150,
        budget_max=600,
        difficulty_level="进阶",
        target_interests=["宠物健康", "冻干", "益生菌", "营养", "猫狗"],
    ),
]


DIRECTION_PRODUCT_LINKS: list[DirectionProductLink] = [
    # 跑步入门
    DirectionProductLink(direction_id="d_running_beginner", product_id="p_001", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_running_beginner", product_id="p_002", product_role="基础搭配", priority=2),
    DirectionProductLink(direction_id="d_running_beginner", product_id="p_006", product_role="功能搭配", priority=3),

    # 手冲咖啡
    DirectionProductLink(direction_id="d_coffee_beginner", product_id="p_004", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_coffee_beginner", product_id="p_005", product_role="收纳搭配", priority=2),

    # 家居收纳
    DirectionProductLink(direction_id="d_home_organizing", product_id="p_005", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_home_organizing", product_id="p_004", product_role="生活方式搭配", priority=2),

    # 护肤入门
    DirectionProductLink(direction_id="d_skincare_starter", product_id="p_009", product_role="入门款", priority=1),
    DirectionProductLink(direction_id="d_skincare_starter", product_id="p_007", product_role="核心商品", priority=2),
    DirectionProductLink(direction_id="d_skincare_starter", product_id="p_011", product_role="核心商品", priority=3),
    DirectionProductLink(direction_id="d_skincare_starter", product_id="p_005", product_role="搭配款", priority=4),

    # 进阶抗老
    DirectionProductLink(direction_id="d_skincare_advanced", product_id="p_008", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_skincare_advanced", product_id="p_010", product_role="核心商品", priority=2),
    DirectionProductLink(direction_id="d_skincare_advanced", product_id="p_007", product_role="基础搭配", priority=3),
    DirectionProductLink(direction_id="d_skincare_advanced", product_id="p_011", product_role="基础搭配", priority=4),

    # 无线降噪耳机
    DirectionProductLink(direction_id="d_tech_audio", product_id="p_013", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_tech_audio", product_id="p_018", product_role="替代款", priority=2),
    DirectionProductLink(direction_id="d_tech_audio", product_id="p_016", product_role="搭配款", priority=3),

    # 桌面生产力
    DirectionProductLink(direction_id="d_tech_workspace", product_id="p_015", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_tech_workspace", product_id="p_017", product_role="核心商品", priority=2),
    DirectionProductLink(direction_id="d_tech_workspace", product_id="p_016", product_role="搭配款", priority=3),
    DirectionProductLink(direction_id="d_tech_workspace", product_id="p_014", product_role="推荐商品", priority=4),

    # 新手养猫
    DirectionProductLink(direction_id="d_pet_new_cat", product_id="p_019", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_pet_new_cat", product_id="p_022", product_role="核心商品", priority=2),
    DirectionProductLink(direction_id="d_pet_new_cat", product_id="p_021", product_role="入门款", priority=3),
    DirectionProductLink(direction_id="d_pet_new_cat", product_id="p_023", product_role="搭配款", priority=4),
    DirectionProductLink(direction_id="d_pet_new_cat", product_id="p_020", product_role="搭配款", priority=5),

    # 宠物健康管理
    DirectionProductLink(direction_id="d_pet_health", product_id="p_021", product_role="核心商品", priority=1),
    DirectionProductLink(direction_id="d_pet_health", product_id="p_020", product_role="核心商品", priority=2),
    DirectionProductLink(direction_id="d_pet_health", product_id="p_024", product_role="进阶款", priority=3),
    DirectionProductLink(direction_id="d_pet_health", product_id="p_019", product_role="搭配款", priority=4),
]


PRODUCT_SYNC_SOURCES: list[ProductSyncSource] = [
    ProductSyncSource(
        source_id="sync_catalog_local",
        name="本地电商商品清单",
        source_type="file",
        location="data/product_catalog_market_export.csv",
        adapter="ecommerce_catalog",
        enabled=True,
        notes="用于演示从本地导出商品清单自动同步到商品库。",
    ),
    ProductSyncSource(
        source_id="sync_amazon_local",
        name="本地 Amazon 热销榜样例",
        source_type="file",
        location="data/amazon_bestsellers_export.csv",
        adapter="amazon_bestsellers",
        enabled=False,
        notes="用于演示 Amazon Bestsellers 风格导出文件的自动同步。",
    ),
]
